Command and DeleteCommand Feature
AY2324S2-CS2113T-T09-2/tp pull request #25
Opened 2024-03-11 09:55 UTC by PureUsagi

Created Command abstract class for future Command classes and DeleteCommand to remove item from inventory.

2024-03-11 10:38 UTC, YHWong20 requested changes

2024-03-11 10:38 UTC, YHWong20 commented on src/main/java/seedu/binbash/command/DeleteCommand.java
> +            Pattern.compile("delete\\s(?<index>\\d+)");
Might need to re-confirm if we are deleting by index or by item name. The draft UG seems to use item name instead.

2024-03-11 10:38 UTC, YHWong20 commented on src/main/java/seedu/binbash/command/DeleteCommand.java
> +    public static final String COMMAND_WORD = "delete";
String constant name in `Command.java` is `COMMAND_STRING`, but here it's `COMMAND_WORD`. 

Not sure if this is intentional. If it is, then this comment can be ignored.

2024-03-11 10:38 UTC, YHWong20 commented on src/main/java/seedu/binbash/ItemList.java
> +        itemList.remove(index - 1);
If I'm not wrong, the `.remove(int index)` method for a List will return us the removed element, so we can probably consider removing the previous line. 

i.e., we can probably merge the two lines into something like `Item removedItem = itemList.remove(index - 1);`?

2024-03-12 07:28 UTC, YHWong20 commented on src/main/java/seedu/binbash/command/DeleteCommand.java
> +            Pattern.compile("delete\\s(?<index>\\d+)");
I think we can probably ignore this comment.

2024-03-12 11:01 UTC, PureUsagi commented on src/main/java/seedu/binbash/ItemList.java
> +        itemList.remove(index - 1);
Okayy, will remove the line.

2024-03-12 11:01 UTC, PureUsagi commented on src/main/java/seedu/binbash/command/DeleteCommand.java
> +    public static final String COMMAND_WORD = "delete";
Oh yea, it's a typo. Forgot to change the variable name.

2024-03-12 11:09 UTC, closed without merging